ArtWarehouse/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;

namespace ArtWarehouse.Controllers
{
    [Route("[controller]")]
    public class InfoController : Controller
    {
        [HttpGet]
        [Route("info-help")]
        public IActionResult InfoHelp()
        {
            TempData["Enter"] = "Yes";
            return View();
        }
    }
}

ArtWarehouse/Controllers/MovementController.cs
using ArtWarehouse.Models.ModelsView;
using ArtWarehouse.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace ArtWarehouse.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class MovementController : Controller
    {
        public IConfiguration Configuration { get; }
        private Documents_DbService _dbService;

        public MovementController(IConfiguration configuration)
        {
            Configuration = configuration;
            _dbService = new Documents_DbService(Configuration);
        }

        public IActionResult Index()
        {
            TempData["Enter"] = "Yes";

            Movement_MV model = new Movement_MV();

            try
            {
                model = _dbService.MovementGoods_Get();
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return View(model);
        }
    }
}

ArtWarehouse/Controllers/PurchasingController.cs
using ArtWarehouse.Models.ModelsView;
using ArtWarehouse.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Linq;

namespace ArtWarehouse.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class PurchasingController : Controller
    {
        public IConfiguration Configuration { get; }

        Warehouse_DbService _warehouse_Db;
        Purchasing_DbService _purchasing_Db;

        public PurchasingController(IConfiguration configuration)
        {
            Configuration = configuration;
            _warehouse_Db = new Warehouse_DbService(Configuration);
            _purchasing_Db = new Purchasing_DbService(Configuration);
        }

        [HttpGet]
        [Route("purchasing-index")]

        public IActionResult Index()
        {
            TempData["Enter"] = "Yes";

            return View();
        }

        [HttpPost]
        [Route("purchasing-form")]

        public IActionResult PurchasingFormIndex(string data)
        {
            TempData["Enter"] = "Yes";

            var goodsIdList = JsonConvert.DeserializeObject<GoodsIdForPurchasingList_MV>(data);

            GoodsCompleteInfo_MV goodsCompleteInfo_MV = new GoodsCompleteInfo_MV();

            try
            {
                goodsCompleteInfo_MV = _warehouse_Db.GoodsWorkList_Get(goodsIdList.GoodsId);
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return View(goodsCompleteInfo_MV);
        }

        [HttpPost]
        [Route("purchasing-order")]
        public IActionResult PurchasingFormOrder(Purchasing_MV data)
        {
            TempData["Enter"] = "Yes";

            if (data.remaining_goods.Where(item => item == null).ToList().Count > 0 
                || data.remaining_goods.Where(item => item == "0").ToList().Count > 0)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка!";
                TempData["ErrorMessage"] = "Проверьте что бы небыло нулевых или пустых значений в заказе.";
                return RedirectToAction("Index", "Error");
            }

            try
            {
                _purchasing_Db.Purchasing_Insert(data);
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка сохранения данных в Базу Данныx.";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return RedirectToAction("Index", "Warehouse");
        }

    }
}

ArtWarehouse/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Dapper;
using System;
using ArtWarehouse.Models.ModelsView;
using ArtWarehouse.Models;
using ArtWarehouse.Models.ErrorModels;
using System.Linq;
using ArtWarehouse.Services;
using Humanizer;
using System.Globalization;

namespace ArtWarehouse.Controllers
{
    [Route("[controller]")]
    public class WarehouseController : Controller
    {
        public IConfiguration Configuration { get; }

        Warehouse_DbService warehouse_Db;
        Sale_DbService sale_Db;


        public WarehouseController(IConfiguration configuration)
        {
            Configuration = configuration;
            warehouse_Db = new Warehouse_DbService(Configuration);
            sale_Db = new Sale_DbService(Configuration);
        }

        [HttpGet]
        [Route("warehouse-Index")]
        public IActionResult Index(string username = null)
        {
            if (username != null)
            {
                TempData["Nickname"] = username;
            }

            TempData["Enter"] = "Yes";

            GoodsCompleteInfo_MV goodsCompleteInfo_MV;

            try
            {
                //if (AutoGenerateSales.FirstSaleAutoGenerate == false)
                //{
                //    AutoGenerateSales.SalesGenerator(warehouse_Db, sale_Db);
                //    AutoGenerateSales.FirstSaleAutoGenerate = true;
                //}

                goodsCompleteInfo_MV = warehouse_Db.GoodsCompleteInfo_Get();
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return View(goodsCompleteInfo_MV);
        }

        [HttpGet]
        [Route("warehouse-Category")]
        public IActionResult CategorySort()
        {
            TempData["Enter"] = "Yes";

            GoodsCompleteInfo_MV goodsCompleteInfo_MV;

            try
            {
                goodsCompleteInfo_MV = warehouse_Db.GoodsCompleteInfo_Get();
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return View(goodsCompleteInfo_MV);
        }

        [HttpGet]
        [Route("warehouse-Maker")]
        public IActionResult MakerSort()
        {
            TempData["Enter"] = "Yes";

            GoodsCompleteInfo_MV goodsCompleteInfo_MV;

            try
            {
                goodsCompleteInfo_MV = warehouse_Db.GoodsCompleteInfo_Get();
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return View(goodsCompleteInfo_MV);
        }

        [HttpGet]
        [Route("warehouse-SearchResult")]
        public IActionResult SearchResult([FromQuery] string searchRequest)
        {
            TempData["Enter"] = "Yes";

            GoodsCompleteInfo_MV goodsCompleteInfo_MV;
            try
            {
                goodsCompleteInfo_MV = warehouse_Db.GoodsCompleteInfo_Get();
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            var searchNameList = goodsCompleteInfo_MV.goodsList.Where(g => g.goods_name.ToLower().Contains(searchRequest.ToLower())).ToList();
            var searchDescrList = goodsCompleteInfo_MV.goodsList.Where(g => g.goods_descr.ToLower().Contains(searchRequest.ToLower())).ToList();

            goodsCompleteInfo_MV.goodsList = searchNameList;

            foreach (var good in searchDescrList)
            {
                if (!goodsCompleteInfo_MV.goodsList.Contains(good))
                {
                    goodsCompleteInfo_MV.goodsList.Add(good);
                }
            }

            return View(goodsCompleteInfo_MV);
        }

        [HttpGet]
        public IActionResult RequestFor_CardOfGoods(int id)
        {
            TempData["Enter"] = "Yes";

            GoodsInfoForCard_MV goodsInfoForCard_MV;

            try
            {
                goodsInfoForCard_MV = warehouse_Db.GoodsInfoForCard_Get(id);
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index", "Error");
            }

            return View(goodsInfoForCard_MV);
        }
    }
}

ArtWarehouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - АртСклад</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
</head>
<body>
    <header class="container header">
        <div class="header-content">
            <div class="main-title-group">
                <div class="main-logo"></div>
                <div class="main-title">Арт-Склад</div>
            </div>
            <nav class="main-navigation">
                @if (TempData["Enter"] != null && TempData["Enter"].ToString() == "Yes")
                {
                    <div>
                        <a class="main-navigation_link main-navigation_link-contacts">
                            <i class="far fa-address-card"></i>
                            Контакты
                        </a>
                    </div>
                    <div>
                        <a asp-controller="Info" asp-action="InfoHelp" class="main-navigation_link main-navigation_link-help">
                            <i class="far fa-question-circle"></i>
                            Помощь
                        </a>
                    </div>
                }
                else
                {
                    <div>
                        <a class="main-navigation_link">
                            <i class="far fa-address-card"></i>
                            Контакты
                        </a>
                    </div>
                    <div>
                        <a class="main-navigation_link">
                            <i class="far fa-question-circle"></i>
                            Помощь
                        </a>
                    </div>

                }
                @if (TempData["Enter"] != null && TempData["Enter"].ToString() == "Yes")
                {
                    <div class="ml-5">
                        <i class="fas fa-user-check"></i>
                        <a id="user-link-nickname" class="main-navigation_link user-link"></a>
                    </div>
                    <div>
                        <i class="fas fa-sign-out-alt"></i>
                        <a id="user-link-exit-from-account" asp-controller="Home" asp-action="Index" class="main-navigation_link">Выход</a>
                    </div>

                }
                else
                {
                    <div class="ml-5">
                        <a class="main-navigation_link user-link">Вход в систему не выполнен!</a>
                    </div>
                    <div>
                        <i class="fas fa-door-closed"></i>
                    </div>
                }
            </nav>
        </div>
        @if (TempData["Enter"] != null && TempData["Enter"].ToString() == "Yes")
        {
            <div class="main-tabs">
                <a class="tab-item" asp-controller="Warehouse" asp-action="Index">Склад</a>
                <a class="tab-item" asp-controller="Purchasing" asp-action="Index">Закупки</a>
                <a class="tab-item" asp-controller="Movement" asp-action="Index">Движение</a>
                <a class="tab-item" asp-controller="Documents" asp-action="Index">Документы</a>
            </div>
        }
        else if (TempData["Enter"] == null || TempData["Enter"].ToString() != "Yes")
        {
            <div class="main-tabs">
                <a class="tab-item">Склад</a>
                <a class="tab-item">Закупки</a>
                <a class="tab-item">Движение</a>
                <a class="tab-item">Документы</a>
            </div>
        }

    </header>
    <div class="container" style="padding: 0">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>