ArtWarehouse/Controllers/PrintController.cs
using ArtWarehouse.Models;
using ArtWarehouse.Models.ModelsView;
using ArtWarehouse.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Rotativa.AspNetCore;
using System.Diagnostics;

namespace ArtWarehouse.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class PrintController : Controller
    {
        public IConfiguration Configuration { get; }

        Warehouse_DbService _warehouse_Db;

        public PrintController(IConfiguration configuration)
        {
            Configuration = configuration;
            _warehouse_Db = new Warehouse_DbService(Configuration);
        }

        [HttpPost]
        [Route("print-index")]
        public IActionResult Index(string data)
        {
            var listForPrint = JsonConvert.DeserializeObject<ListForPrint_MV>(data);

            GoodsCompleteForPrint_MV goodsComplete = new GoodsCompleteForPrint_MV();
            GoodsCompleteInfo_MV goodsCompleteInfo_MV;
            try
            {
                if (listForPrint.GoodsId.Length == 0)
                {
                    goodsCompleteInfo_MV = _warehouse_Db.GoodsCompleteInfo_Get();
                }
                else
                {
                    goodsCompleteInfo_MV = _warehouse_Db.GoodsWorkList_Get(listForPrint.GoodsId);
                }
                goodsComplete.GoodsList = (List<Goods_Model>)goodsCompleteInfo_MV.goodsList;
                goodsComplete.CategoriesList = (List<GoodsCategory_Model>)goodsCompleteInfo_MV.categoriesList;
                goodsComplete.MakersList = (List<Maker_Model>)goodsCompleteInfo_MV.makersList;
                goodsComplete.PrintViewType = listForPrint.PrintViewType;
            }
            catch (Exception ex)
            {
                TempData["ErrorSoursPageMessage"] = "Ошибка получения данных из Базы Данных";
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }

            return View(goodsComplete);
        }

        [HttpPost]
        [Route("print-pdf")]
        public IActionResult CreatePdfFile(GoodsCompleteForPrint_MV goodsComplete) 
        {
            GoodsCompleteForPrint_MV model = goodsComplete;

            var pdfContentTask = new ViewAsPdf("PrintPage", model)
            {
                PageSize = Rotativa.AspNetCore.Options.Size.A4, // Формат страницы
                PageMargins = new Rotativa.AspNetCore.Options.Margins(0, 0, 0, 0), // Отступы в мм
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait, // Горизонтальная ориентация
            }.BuildFile(ControllerContext);

            try
            {
                pdfContentTask.Wait(); // Ждем завершения задачи
                var pdfContent = pdfContentTask.Result; // Получаем результат из задачи
                System.IO.File.WriteAllBytes("document.pdf", pdfContent);
            }
            catch (AggregateException ex)
            {
                foreach (var innerEx in ex.InnerExceptions)
                {
                    Debug.WriteLine($"Inner Exception: {innerEx.Message}");
                }
            }


            return RedirectToAction("Index", "Warehouse");
        }

        [HttpPost]
        [Route("print-doc-preview")]
        public IActionResult PrintDocPreview(string data)
        {
            return View();
        }

    }
}

ArtWarehouse/Views/Print/Index.cshtml
@model ArtWarehouse.Models.ModelsView.GoodsCompleteForPrint_MV
@{
    ViewData["Title"] = "На печать";
}
@{
    Layout = null;
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/preview-pages/preview-page-goods-list.css" />
</head>

<div class="container preview-print-page">
    <header class="preview-header mb-3 pt-3">
        <div class="preview-title-group">
            <div class="preview-logo"></div>
            <div class="preview-title">Арт-Склад</div>
        </div>
    </header>
    <main>
        @if (Model == null)
        {
            <p>Ошибка при подготовке документа.</p>
            <a class="btn btn-danger text-left w-25" asp-controller="Warehouse" asp-action="Index">Закрыть</a>
        }

        @if(Model.PrintViewType == ArtWarehouse.Models.Enums.PrintViewType.AllList)
        {
            <table class="table table-bordered table-striped" style="width: 100%">
                <thead>
                    <tr>
                        <th>
                            Наименование
                        </th>
                        <th>
                            Категория
                        </th>
                        <th class="text-center pl-0 pr-0">
                            Остаток
                        </th>
                        <th class="text-center pl-0 pr-0">
                            Дата изменения
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.GoodsList)
                    {
                        <tr class="goods-row" data-goodsid="@item.goods_id">
                            <td class="goods-cell" style="width: 40%">
                                @item.goods_name
                            </td>
                            <td style="width: 40%">
                                @Model.CategoriesList.FirstOrDefault(u => u.category_id == item.goods_category_id).category_name
                            </td>
                            <td style="width: 7%" class="text-center">
                                @item.remaining_goods
                            </td>
                            <td style="width: 13%" class="text-center">
                                @item.update_date.ToShortDateString()
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        }

        @if (Model.PrintViewType == ArtWarehouse.Models.Enums.PrintViewType.CategorySort)
        {
            @foreach (var category in Model.CategoriesList)
            {
                @if (Model.GoodsList.Where(u => u.goods_category_id == category.category_id).Count() == 0)
                {
                    continue;
                }

                <h1 class="preview-category-title">@category.category_name</h1>
                <table class="table table-bordered table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th>
                                Наименование
                            </th>
                            <th>
                                Производитель
                            </th>
                            <th class="text-center pl-0 pr-0">
                                Остаток
                            </th>
                            <th class="text-center pl-0 pr-0">
                                Дата изменения
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.GoodsList.Where(u => u.goods_category_id == category.category_id))
                        {
                            <tr class="goods-row" data-goodsid="@item.goods_id">
                                <td style="width: 40%">
                                    @item.goods_name
                                </td>
                                <td style="width: 40%">
                                    @Model.MakersList.FirstOrDefault(u => u.maker_id == item.maker_id).maker_name
                                </td>
                                <td style="width: 7%" class="text-center">
                                    @item.remaining_goods
                                </td>
                                <td style="width: 13%" class="text-center">
                                    @item.update_date.ToShortDateString()
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }

        }
        @if (Model.PrintViewType == ArtWarehouse.Models.Enums.PrintViewType.MakerSort)
        {
            @foreach (var maker in Model.MakersList)
            {
                @if (Model.GoodsList.Where(u => u.maker_id == maker.maker_id).Count() == 0)
                {
                    continue;
                }

                <h1 class="preview-category-title">@maker.maker_name</h1>
                <table class="table table-bordered table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th>
                                Наименование
                            </th>
                            <th>
                                Категория
                            </th>
                            <th class="text-center pl-0 pr-0">
                                Остаток
                            </th>
                            <th class="text-center pl-0 pr-0">
                                Дата изменения
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.GoodsList.Where(u => u.maker_id == maker.maker_id))
                        {
                            <tr class="goods-row" data-goodsid="@item.goods_id">
                                <td style="width: 40%">
                                    @item.goods_name
                                </td>
                                <td style="width: 40%">
                                    @Model.CategoriesList.FirstOrDefault(u => u.category_id == item.goods_category_id).category_name
                                </td>
                                <td style="width: 7%" class="text-center">
                                    @item.remaining_goods
                                </td>
                                <td style="width: 13%" class="text-center">
                                    @item.update_date.ToShortDateString()
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }

        }
    </main>
    <footer class="preview-footer pt-5 pb-5">
        <span class="mr-4">
            <i class="fas fa-calendar-alt"></i>
            &nbsp; Документ создан: @DateTime.Now.ToLocalTime()
        </span>
        <span class="mr-4">
            <i class="fas fa-info-circle"></i>
            &nbsp; Предназначен для использования только внутри компании.
        </span>
        <span>
            <i class="fas fa-mobile-alt"></i>
            &nbsp; Телефон менеджера: 755-55-108
        </span>
    </footer>

    <div class="preview-btn-block pb-5">
        <a class="item-control btn btn-info btn-sm w-25 mr-3"
           asp-controller="Print"
           asp-action="CreatePdfFile">
           Печать
       </a>
        <a class="item-control btn btn-secondary btn-sm w-25"
           asp-controller="Warehouse"
           asp-action="Index">
           Отмена
       </a>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
}

ArtWarehouse/Views/Print/PrintPage.cshtml
@model ArtWarehouse.Models.ModelsView.GoodsCompleteForPrint_MV
@{
    ViewData["Title"] = "На печать";
}
@{
    Layout = null;
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/css/preview-pages/preview-page-goods-list.css" />
</head>

<div class="container preview-print-page">

    <div class="print-pdf" id="PrintPDF">
        <header class="preview-header mb-3 pt-3">
            <div class="preview-title-group">
                <div class="preview-logo"></div>
                <div class="preview-title">Арт-Склад</div>
            </div>
        </header>
        <main>
            @if (Model == null)
            {
                <p>Ошибка при подготовке документа.</p>
                <a class="btn btn-danger text-left w-25" asp-controller="Warehouse" asp-action="Index">Закрыть</a>
            }

            @if (Model.PrintViewType == ArtWarehouse.Models.Enums.PrintViewType.AllList)
            {
                <table class="table table-bordered table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th>
                                Наименование
                            </th>
                            <th>
                                Категория
                            </th>
                            <th class="text-center pl-0 pr-0">
                                Остаток
                            </th>
                            <th class="text-center pl-0 pr-0">
                                Дата изменения
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.GoodsList)
                        {
                            <tr class="goods-row" data-goodsid="@item.goods_id">
                                <td class="goods-cell" style="width: 40%">
                                    @item.goods_name
                                </td>
                                <td style="width: 40%">
                                    @Model.CategoriesList.FirstOrDefault(u => u.category_id == item.goods_category_id).category_name
                                </td>
                                <td style="width: 7%" class="text-center">
                                    @item.remaining_goods
                                </td>
                                <td style="width: 13%" class="text-center">
                                    @item.update_date.ToShortDateString()
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            }

            @if (Model.PrintViewType == ArtWarehouse.Models.Enums.PrintViewType.CategorySort)
            {
                @foreach (var category in Model.CategoriesList)
                {
                    @if (Model.GoodsList.Where(u => u.goods_category_id == category.category_id).Count() == 0)
                    {
                        continue;
                    }

                    <h1 class="preview-category-title">@category.category_name</h1>
                    <table class="table table-bordered table-striped" style="width: 100%">
                        <thead>
                            <tr>
                                <th>
                                    Наименование
                                </th>
                                <th>
                                    Производитель
                                </th>
                                <th class="text-center pl-0 pr-0">
                                    Остаток
                                </th>
                                <th class="text-center pl-0 pr-0">
                                    Дата изменения
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.GoodsList.Where(u => u.goods_category_id == category.category_id))
                            {
                                <tr class="goods-row" data-goodsid="@item.goods_id">
                                    <td style="width: 40%">
                                        @item.goods_name
                                    </td>
                                    <td style="width: 40%">
                                        @Model.MakersList.FirstOrDefault(u => u.maker_id == item.maker_id).maker_name
                                    </td>
                                    <td style="width: 7%" class="text-center">
                                        @item.remaining_goods
                                    </td>
                                    <td style="width: 13%" class="text-center">
                                        @item.update_date.ToShortDateString()
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }

            }
            @if (Model.PrintViewType == ArtWarehouse.Models.Enums.PrintViewType.MakerSort)
            {
                @foreach (var maker in Model.MakersList)
                {
                    @if (Model.GoodsList.Where(u => u.maker_id == maker.maker_id).Count() == 0)
                    {
                        continue;
                    }

                    <h1 class="preview-category-title">@maker.maker_name</h1>
                    <table class="table table-bordered table-striped" style="width: 100%">
                        <thead>
                            <tr>
                                <th>
                                    Наименование
                                </th>
                                <th>
                                    Категория
                                </th>
                                <th class="text-center pl-0 pr-0">
                                    Остаток
                                </th>
                                <th class="text-center pl-0 pr-0">
                                    Дата изменения
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.GoodsList.Where(u => u.maker_id == maker.maker_id))
                            {
                                <tr class="goods-row" data-goodsid="@item.goods_id">
                                    <td style="width: 40%">
                                        @item.goods_name
                                    </td>
                                    <td style="width: 40%">
                                        @Model.CategoriesList.FirstOrDefault(u => u.category_id == item.goods_category_id).category_name
                                    </td>
                                    <td style="width: 7%" class="text-center">
                                        @item.remaining_goods
                                    </td>
                                    <td style="width: 13%" class="text-center">
                                        @item.update_date.ToShortDateString()
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }

            }
        </main>
        <footer class="preview-footer pt-5 pb-5">
            <div class="mr-4">
                <i class="fas fa-calendar-alt"></i>
                &nbsp; Документ создан: @DateTime.Now.ToLocalTime()
            </div>
            <div class="mr-4">
                <i class="fas fa-info-circle"></i>
                &nbsp; Предназначен для использования только внутри компании.
            </div>
            <div>
                <i class="fas fa-mobile-alt"></i>
                &nbsp; Телефон менеджера: 755-55-108
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</div>